### ISSUE TITLE
notifications for referenda only

### ISSUE THREAD

**Issue by nicolasochem** [Premiurly/polkassembly#108]
I typically vote on referenda but don't pay much attention to motion/tips/etc. It would be nice to only receive emails for new referenda instead of everything that happens.

Add a toggle

```
notified for new referendum on/off
notified for new proposal in council/motion/other events on/off
```

**Comment by alphainfinitus** [comment]
We are excited to announce that our notification engine has undergone a comprehensive UI overhaul in https://github.com/polkassembly/polkassembly/pull/297, incorporating the requested functionality. Users now have the ability to fine-tune their notification preferences and select the specific types of events they wish to be notified about. With this granular level of control, you can now choose to receive notifications solely for new referenda while opting out of notifications related to council proposals, motions, and other events.

By utilizing these toggle options, you can tailor your notifications to align with your specific interests and engagement preferences.

For more details and instructions please check out the announcement tweet: https://twitter.com/polk_gov/status/1673731519209193478

We appreciate your patience and understanding during the implementation process. Your feedback is invaluable in helping us refine and improve the Polkassembly platform. If you encounter any issues or have further suggestions, please don't hesitate to reach out to our support team.

Thank you for being an active member of the Polkassembly community, and we look forward to your continued participation in shaping the future of decentralized governance.

Best regards,

Mridul
Polkassembly Team
