### ISSUE TITLE
Integrate Talisman Subwallet and other wallets.

### ISSUE THREAD

**Issue by niklabh** [Premiurly/polkassembly#121]
Integrate Talisman Subwallet and other wallets for polkassembly

**Comment by RyanDinh8** [comment]
It's a good idea for users who do not use Polkadot JS wallet can sign-up and log in to their accounts on the Polkassembly app. (For example SubWallet users). 

<img width="1268" alt="Screen Shot 2022-05-12 at 17 29 15" src="https://user-images.githubusercontent.com/102496727/168051920-89c3d66a-624d-41bf-bd67-f62a2da7de66.png">

<img width="1269" alt="Screen Shot 2022-05-12 at 15 52 09" src="https://user-images.githubusercontent.com/102496727/168052048-f844da37-80eb-4e44-8176-684aad6b05e8.png">

**Solution:**
There should be a wallet section for users to choose which wallet they want to connect to the app.

Please see our demo and integration instructions in the link below:
https://docs.subwallet.app/integration/integration-instructions

Thank you very much and we look forward to the integration.

Ryan.

**Comment by antonkhvorov** [comment]
Please also include Nova Wallet (novawallet.io) to that integration 🙏
Brand-kit:
https://drive.google.com/drive/u/1/folders/10QbuBxVSASpUVYSGcW3e2gY4EzcR6p46

**Comment by pedroapfilho** [comment]
Hello @RyanDinh8, could you please provide me the SubWallet logo in SVG? I can't find it anywhere.

**Comment by RyanDinh8** [comment]
> Hello @RyanDinh8, could you please provide me the SubWallet logo in SVG? I can't find it anywhere.

Hi @pedroapfilho, please find it here: https://drive.google.com/drive/u/0/folders/13fvFrN4fQPUautfOiH3AspSeTtVf7aAW

Thank you very much.

**Comment by chevdor** [comment]
The current Talisman integration does not work properly, here is the issue in image:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/738724/184660728-54f77d24-0269-4feb-ab36-427c7874a3d4.png">

I select Polkadot.js and here is what pops-up:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/738724/184660863-b0ac1233-637a-4ea1-938e-2db9100e9f32.png">

So Talisman comes unfortunately too strong here and this has a negative impact on Talisman: I would like to test Talisman but having accounts in Polkadot.js, I am forced to disable the Talisman extension to be able to login.

**Comment by chevdor** [comment]
Moreover, even logged in using PolkadotJS, Talisman pops up when it comes to voting for instance.
That being despite the fact that the logged in account is not even in my accounts in Talisman.

**Comment by niklabh** [comment]
This PR will fix the issue https://github.com/Premiurly/polkassembly/pull/180

**Comment by alphainfinitus** [comment]
Talisman, Subwallet Metamask and Nova Wallet have been added.
Wallet intergration has been fixed.
