### ISSUE TITLE
Polkascan links are broken

### ISSUE THREAD

**Issue by semuelle** [Premiurly/polkassembly#124]
How to reproduce:

1. Open a referendum, e.g. https://kusama.polkassembly.io/referendum/188
2. Click `Show in Polkascan` (links to `https://polkascan.io/kusama/democracy/referendum/188`)
3. Get `Sorry, page not found!`

**Comment by alphainfinitus** [comment]
Hi @semuelle,

thank you for bringing this to our attention. We have investigated the issue and have decided to no longer show polkascan links on our platform. We apologize for any inconvenience this may have caused. Please let us know if you have any further questions or concerns.
