### ISSUE TITLE
Older proposals fail loading

### ISSUE THREAD

**Issue by chevdor** [Premiurly/polkassembly#183]
From https://kusama.polkassembly.io/motions

Click

<img width="716" alt="image" src="https://user-images.githubusercontent.com/738724/186851626-b9d4e4e2-c7a3-486f-b70c-041f01755183.png">

Until you reach the bottom, it will error before you do so:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/738724/186851497-c0c88aa6-0076-4b58-86d9-6b6edeb2ba34.png">

**Comment by chevdor** [comment]
Porposal #145 is the last I could see.

**Comment by alphainfinitus** [comment]
Resolved with [https://github.com/Premiurly/polkassembly/pull/210](url) for polkadot, we'll soon be deploying for Kusama.
