### ISSUE TITLE
Upcoming events section [Improvements]

### ISSUE THREAD

**Issue by dot-alert** [Premiurly/polkassembly#192]
Hello,

Just letting you know that the "Upcoming events" section of Polkassembly is tricky to navigate as the dates are all mixed up and not displayed chronologically.

![Polkassemblybug](https://user-images.githubusercontent.com/112253893/190972975-435c1080-a1b2-4c67-93f3-da09496011f8.JPG)
![Polkassemblybug2](https://user-images.githubusercontent.com/112253893/190973112-b83b1b3f-bb3c-4319-a4e4-3fe36481136a.JPG)

It would be good to see upcoming events only, and not past events.
Thanks!  🤝🏿

**Comment by alphainfinitus** [comment]
Added in [https://github.com/Premiurly/polkassembly/pull/208](url)
