### ISSUE TITLE
Discord Link on Polkassembly Website expired

### ISSUE THREAD

**Issue by benjichat** [Premiurly/polkassembly#211]
The following links on https://polkadot.polkassembly.io/ are broken:

Top bar: https://discord.com/invite/wGUDt2p

<img width="1257" alt="Screenshot 2022-10-03 at 20 00 57" src="https://user-images.githubusercontent.com/63160791/193646718-4d7eec5d-d091-42e9-a4b8-4cfd16b9d78f.png">

Footer: https://discord.com/invite/wGUDt2p

<img width="247" alt="Screenshot 2022-10-03 at 20 01 36" src="https://user-images.githubusercontent.com/63160791/193646843-5072de28-e11a-47ab-8579-8a3946993e52.png">

**Comment by niklabh** [comment]
https://github.com/Premiurly/polkassembly/pull/216

**Comment by niklabh** [comment]
fixed
