### ISSUE TITLE
Critical bug on Polkassembly.

### ISSUE THREAD

**Issue by dot-alert** [Premiurly/polkassembly#213]
Hello all,

There is some critical bug happening on Polkassembly right now.
I am logged in as @rtti and have access to his profile/details.

![Polkassembly_error](https://user-images.githubusercontent.com/112253893/194687418-f997137c-fbbc-4005-9981-8aae9e8404b2.JPG)
![Polkassembly_error2](https://user-images.githubusercontent.com/112253893/194687472-1d708f30-217e-4c56-9f3a-9443a9abc291.JPG)

Please look into this ASAP.
Thanks.

**Comment by Parambir17** [comment]
Hi,

We are fixing this asap! Thank you for flagging it :)

**Comment by niklabh** [comment]
Fixed
