### ISSUE TITLE
Formatting issues when using bullet points/numbers list on contextual information

### ISSUE THREAD

**Issue by rrtti** [Premiurly/polkassembly#249]
What I see when I draft the contextual information:

<img width="1125" alt="Screenshot 2022-11-14 at 11 05 37" src="https://user-images.githubusercontent.com/22815262/201634152-3abf6530-d2f6-4a33-999f-23dca13750e9.png">

What I see when I post the contextual information:

<img width="815" alt="Screenshot 2022-11-14 at 11 05 25" src="https://user-images.githubusercontent.com/22815262/201634218-db2ddb8d-f2aa-4077-aad9-1828bf15f424.png">

As you can see on the second screenshot, the use of bullet points and numbers do not appear once you hit Publish.

**Comment by chrisdcosta** [comment]
I'd add also on based on [Referendum #85](https://polkadot.polkassembly.io/referendum/85) That the Markdown formatting is all over the place! It seems that the font sizes need tuning.

Would recommend looking at the `>` quote section and `#` hash headlines.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1393274/201782812-1746c9a1-d704-4208-8198-8a6bfa3e5cfb.png">

**Comment by niklabh** [comment]
Fixed, please check
