### ISSUE TITLE
Support for referenda without preimage(Inlined call)

### ISSUE THREAD

**Issue by olanod** [Premiurly/polkassembly#344]
Our referendum 77 doesn't show up in the website, likely because it uses the Inline bounded call?
```
{
  Ongoing: {
    track: 34
    origin: {
      Origins: BigSpender
    }
    proposal: {
      Inline: 0x12030f0044b643bd4c21004896aa6b146417590bd0191a7fe9677e64347e5d6f3d70bca9ded984c2c5c84e
    }
    enactment: {
      After: 100
    }
    submitted: 16,336,895
    submissionDeposit: {
      who: EDVirtoiVjAv8HFZwSGbiBcY6P4kDFba9VKsBS911Aw8evX
      amount: 33,333,333,333
    }
    decisionDeposit: {
      who: EDVirtoiVjAv8HFZwSGbiBcY6P4kDFba9VKsBS911Aw8evX
      amount: 13,333,333,333,200
    }
    deciding: null
    ...
  }
}
```

**Comment by alphainfinitus** [comment]
Thank you for bringing this issue to our attention. Our team has identified and resolved the problem with the referendum 77 not showing up on the website, which has now been corrected. We apologize for any inconvenience this may have caused and appreciate your patience while we worked to fix the issue. If you have any further questions or concerns, please don't hesitate to reach out.
