### ISSUE TITLE
I’ve submitted "DotsamaPrague 2022" proposal and it’s nowhere?

### ISSUE THREAD

**Issue by helloitsdamsky** [Premiurly/polkassembly#378]
I’m 100% sure under this link https://polkadot.polkassembly.io/post/1741  there was submitted discussion by me on the topic above. But it’s different item there?

**Comment by alphainfinitus** [comment]
Thanks for raising this issue. It's been resolved and the issue is now closed. If you have any more issues, feel free to create a new one. Thanks!
