### ISSUE TITLE
Block Number Hyperlinks are Broken on the Timeline pages

### ISSUE THREAD

**Issue by x676f64** [Premiurly/polkassembly#380]
See https://polkadot.polkassembly.io/referendum/116 as an example, click on the `Timeline` tab and click on any linked Block.

The generated links to blocks in the timeline are incorrect. An example of the incorrect URL: https://polkadot.subscan.io/15245977

The correct URL is: https://polkadot.subscan.io/block/15245977

**Comment by x676f64** [comment]
Weird because it looks correct here https://github.com/Premiurly/polkassembly/blob/a3768678aa5f9ba87f5f76a61bd30eb713289234/front-end/src/components/Post/Tabs/PostTimeline/TimelineContainer.tsx#L83-L85 maybe some sort or regression in Prod?

**Comment by alphainfinitus** [comment]
Hi @x676f64 , thank you for raising the issue. This is fixed with : [https://github.com/polkassembly/polkassembly/pull/201](https://github.com/polkassembly/polkassembly/pull/201)
