### ISSUE TITLE
Screen gets frozen at first load

### ISSUE THREAD

**Issue by kukabi** [Premiurly/polkassembly#70]
When I first open the site, all the components of the page are frozen while it's trying to download the identities. I can scroll the page, but links cannot be clicked, and the mouse pointer also doesn't change to a pointer over links.

Steps to reproduce:

- Go to [https://kusama.polkassembly.io/motions](https://kusama.polkassembly.io/motions).
- Try to click on links while there's still no identities loaded on the posts.

**Comment by alphainfinitus** [comment]
We have now fixed this issue.

In addition, we will be releasing a better and more responsive UI super soon!
