### ISSUE TITLE
UI views are not loaded starting at the top

### ISSUE THREAD

**Issue by NachoPal** [Premiurly/polkassembly#97]
When clicking in one of the Latest Activity, the new view does not start at the top of it.

It happens in general for the whole website each time a new view is loaded.

This issue generates a bad UX forcing the user to scroll up every time a new view is loaded.

**Comment by alphainfinitus** [comment]
Thank you for bringing the issue to our attention.
We have made the required adjustments to ensure that every time a new view is loaded, it starts at the top as expected.

We appreciate your patience and understanding throughout this process. Your valuable feedback plays a crucial role in helping us identify and address such issues promptly, ensuring a better experience for all users.

Should you encounter any further concerns or have any additional feedback, please don't hesitate to reach out to us. We are here to assist you.

Thank you for your continued support.

Best regards,

Mridul
Polkassembly
